FROM node:20-alpine

RUN npm install -g nodemon

WORKDIR /app

COPY package.json .
COPY projects/worldBank/package.json ./projects/worldBank/package.json
COPY projects/fileManagerClient/package.json ./projects/fileManagerClient/package.json
COPY projects/eventBus/package.json ./projects/eventBus/package.json

RUN npm install

COPY projects/eventBus ./projects/eventBus
COPY projects/worldBank ./projects/worldBank
COPY projects/fileManagerClient ./projects/fileManagerClient

CMD ["npm", "run", "worldBank"]
