FROM python:3.10-slim

WORKDIR /app/projects/

RUN pip install --no-cache-dir pymupdf
RUN pip install --no-cache-dir boto3
RUN pip install --no-cache-dir pika
RUN pip install --no-cache-dir requests
COPY projects/fileManagerClientPy ./fileManagerClientPy
COPY projects/eventBusPy ./eventBusPy
COPY projects/pII/ ./pII

CMD ["python3","-m", "pII.main"]