FROM python:3.10-slim

WORKDIR /app/projects/

RUN pip install --no-cache-dir pymupdf
RUN pip install --no-cache-dir boto3
RUN pip install --no-cache-dir pika
RUN pip install --no-cache-dir requests
RUN pip install --no-cache-dir pillow
COPY projects/fileManagerClientPy ./fileManagerClientPy
COPY projects/eventBusPy ./eventBusPy
COPY projects/pII/ ./pII

CMD ["python3","-u","-m", "pII.main"]