FROM node:20-alpine

WORKDIR /app

COPY package.json .
COPY reBuild/filesManager/package.json ./reBuild/filesManager/package.json
COPY reBuild/shared/package.json ./reBuild/shared/package.json

RUN npm install

COPY reBuild/shared ./reBuild/shared
COPY reBuild/filesManager ./reBuild/filesManager

CMD ["npm", "run", "filesManager"]
