services:
  download_links:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/downloadLinks/dockerfile-pro
    container_name: downloadLinks
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  extracted_text:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/extractedText/dockerfile
    container_name: extracted_text
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  download:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/download/dockerfile-pro
    container_name: download
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  events:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/events/dockerfile-pro
    container_name: events
    ports:
      - 3001:3001
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  post_download:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/postDownloadPy/dockerfile-pro
    container_name: postDownloadPy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  extracted_text_analyzer:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/extractedTextAnalyzer/dockerfile-pro
    container_name: extractedTextAnalyzer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ai_text_analyzer:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/aiTextAnalyzer/dockerfile-pro
    container_name: aiTextAnalyzer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  auth:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/auth/dockerfile-pro
    container_name: auth
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  insert_data:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/insertData/dockerfile-pro
    container_name: insertData
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  files_manager:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/filesManager/dockerfile-pro
    container_name: filesManager
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  export_to_json:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/exportToJson/dockerfile-pro
    container_name: exportToJson
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  upload_files:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/uploadFiles/dockerfile-pro
    container_name: uploadFiles
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pii:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./projects/pII/dockerfile-pro
    container_name: pii
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
