{
 "title": "Informacion Dominicana",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Post download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"postDownload\"}\n  |= \"eventBusInternalLog\"\n  != \"eventBusInternalRetryError\"\n  != \"eventBusMaxInternalRetryError\"\n  [1m]\n)\n"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({container_name=\"postDownload\"} |= `eventBusInternalLog` |= `eventBusInternalRetryError` [1m])"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"postDownload\"}\n  |= \"eventBusInternalLog\"\n  |= \"eventBusMaxInternalRetryError\"\n  [1m]\n)\n"
    }
   ]
  },
  {
   "title": "Extracted Text",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"extractedText\"}\n  |= \"eventBusInternalLog\"\n  != \"eventBusInternalRetryError\"\n  != \"eventBusMaxInternalRetryError\"\n  [1m]\n)\n"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({container_name=\"extractedText\"} |= `eventBusInternalLog` |= `eventBusInternalRetryError` [1m])"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"extractedText\"}\n  |= \"eventBusInternalLog\"\n  |= \"eventBusMaxInternalRetryError\"\n  [1m]\n)\n"
    }
   ]
  },
  {
   "title": "Analyze Extracted Texts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"analyzeExtractedText\"}\n  |= \"eventBusInternalLog\"\n  != \"eventBusInternalRetryError\"\n  != \"eventBusMaxInternalRetryError\"\n  [1m]\n)\n"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"analyzeExtractedText\"}\n  |= \"eventBusInternalLog\"\n  |= \"eventBusInternalRetryError\"\n  [1m]\n)"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"analyzeExtractedText\"}\n  |= \"eventBusInternalLog\"\n  |= \"eventBusMaxInternalRetryError\"\n  [1m]\n)\n"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"events\"}\n  |= \"eventBusInternalLog\"\n  != \"eventBusInternalRetryError\"\n  != \"eventBusMaxInternalRetryError\"\n  [1m]\n)\n"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({container_name=\"events\"} |= `eventBusInternalLog` |= `eventBusInternalRetryError` [1m])"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"events\"}\n  |= \"eventBusInternalLog\"\n  |= \"eventBusMaxInternalRetryError\"\n  [1m]\n)\n"
    }
   ]
  },
  {
   "title": "Insert Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"insertData\"}\n  |= \"eventBusInternalLog\"\n  != \"eventBusInternalRetryError\"\n  != \"eventBusMaxInternalRetryError\"\n  != \"eventBusInternalError\"\n  [1m]\n)\n"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"insertData\"}\n  |= \"eventBusInternalLog\"\n  |= \"eventBusInternalError\"\n  [1m]\n)"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {container_name=\"insertData\"}\n  |= \"eventBusInternalLog\"\n  |= \"eventBusMaxInternalRetryError\"\n  [1m]\n)\n"
    }
   ]
  }
 ]
}