FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    ffmpeg \
    wget \
    && rm -rf /var/lib/apt/lists/*

COPY projects/extractedText/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir watchdog

COPY projects/eventBusPy/ ./eventBusPy/
COPY projects/fileManagerClientPy/ ./fileManagerClientPy/
COPY projects/extractedText/ ./extractedText

CMD ["python3","-u","-m", "extractedText.main"]