FROM node:20-alpine

WORKDIR /app

COPY package.json .
COPY projects/download/package.json ./projects/download/package.json    
COPY projects/fileManagerClient/package.json ./projects/fileManagerClient/package.json
COPY projects/eventBus/package.json ./projects/eventBus/package.json

RUN npm install

COPY projects/eventBus ./projects/eventBus
COPY projects/download ./projects/download
COPY projects/fileManagerClient ./projects/fileManagerClient

CMD ["npm", "run", "download"]