FROM node:20-alpine

WORKDIR /app

COPY package.json .

RUN ls

RUN npm install

RUN touch main.js
COPY projects/fileManagerClient ./projects/fileManagerClient
COPY projects/eventBus ./projects/eventBus
COPY projects/download ./projects/download

CMD ["npm", "run", "download"]