FROM node:20-alpine

WORKDIR /app

COPY package.json .

RUN ls

RUN npm install

RUN touch main.js
COPY projects/filesAccess ./projects/filesAccess
COPY projects/eventBus ./projects/eventBus
COPY projects/analyzeExtractedText ./projects/analyzeExtractedText

CMD ["npm", "run", "analyzeExtractedText"]