FROM node:20-alpine

WORKDIR /app

RUN npm install -g nodemon

COPY package.json .
COPY projects/aiTextAnalyze/package.json ./projects/aiTextAnalyze/package.json    
COPY projects/fileManagerClient/package.json ./projects/fileManagerClient/package.json
COPY projects/eventBus/package.json ./projects/eventBus/package.json

RUN npm install

COPY projects/eventBus ./projects/eventBus
COPY projects/aiTextAnalyze ./projects/aiTextAnalyze
COPY projects/fileManagerClient ./projects/fileManagerClient

CMD ["nodemon", "run", "./projects/aiTextAnalyze"]