FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    ffmpeg \
    wget \
    && rm -rf /var/lib/apt/lists/*

COPY projects/extractedTextV2/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir watchdog

COPY projects/extractedTextV2/app/ .

ENV PATH="/usr/local/bin:${PATH}"

CMD ["sleep", "3000"]
