FROM node:20-alpine

WORKDIR /app

COPY package.json .
COPY filesManager/package.json ./filesManager/package.json
RUN npm install && cd filesManager && npm install

COPY shared ./shared
COPY filesManager ./filesManager

CMD ["node", "./filesManager/main.js"]
