FROM node:20-alpine

WORKDIR /app

COPY package.json .
COPY projects/filesManager/package.json ./projects/filesManager/package.json

RUN npm install

COPY projects/filesManager ./projects/filesManager

CMD ["npm", "run", "filesManager"]