FROM node:20-alpine

WORKDIR /app

COPY package.json .
COPY projects/events/package.json ./projects/events/package.json    
COPY projects/fileManagerClient/package.json ./projects/fileManagerClient/package.json
COPY projects/eventBus/package.json ./projects/eventBus/package.json

RUN npm install

COPY projects/eventBus ./projects/eventBus
COPY projects/events ./projects/events
COPY projects/fileManagerClient ./projects/fileManagerClient

RUN sleep 5

CMD ["npm", "run", "events"]