FROM node:20-slim

RUN apt-get update && apt-get install -y \
  chromium \
  libasound2 \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libdbus-1-3 \
  libdrm2 \
  libgbm1 \
  libglib2.0-0 \ 
  libnspr4 \
  libnss3 \
  libu2f-udev \ 
  libvulkan1 \
  libx11-6 \
  libx11-xcb1 \
  libxcb1 \
  libxcomposite1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxkbcommon0 \
  libxrandr2 \
  xdg-utils \
  fonts-liberation \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libatspi2.0-0 \
  libcairo2 \
  wget \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json .
COPY projects/downloadLinks/package.json ./projects/downloadLinks/package.json    
COPY projects/fileManagerClient/package.json ./projects/fileManagerClient/package.json
COPY projects/eventBus/package.json ./projects/eventBus/package.json

RUN npm install

COPY projects/eventBus ./projects/eventBus
COPY projects/downloadLinks ./projects/downloadLinks
COPY projects/fileManagerClient ./projects/fileManagerClient

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium"

CMD ["npm", "run", "downloadLinks"]