FROM node:20-alpine

WORKDIR /app

COPY package.json .
COPY projects/exportToJson/package.json ./projects/exportToJson/package.json    
COPY projects/fileManagerClient/package.json ./projects/fileManagerClient/package.json
COPY projects/eventBus/package.json ./projects/eventBus/package.json

RUN npm install --omit=dev

COPY projects/eventBus ./projects/eventBus
COPY projects/exportToJson ./projects/exportToJson
COPY projects/fileManagerClient ./projects/fileManagerClient

CMD ["npm", "run", "exportToJson-pro"]