FROM node:20-alpine

WORKDIR /app

COPY package.json .
COPY projects/fullAIProcess/package.json ./projects/fullAIProcess/package.json
COPY projects/fileManagerClient/package.json ./projects/fileManagerClient/package.json
COPY projects/eventBus/package.json ./projects/eventBus/package.json

RUN npm install --omit=dev

COPY projects/eventBus ./projects/eventBus
COPY projects/fullAIProcess ./projects/fullAIProcess
COPY projects/fileManagerClient ./projects/fileManagerClient

CMD ["npm", "run", "fullAIProcess-pro"]
